In [3]:
import pandas as pd

Load the data from the csv file into the dataframe of pandas.

In [4]:
global_df = pd.read_csv('Global EV Data 2024.csv')
global_df

,region,category,parameter,mode,powertrain,year,unit,value
0,Australia,Historical,EV stock share,Cars,EV,2011,percent,3.900000e-04
1,Australia,Historical,EV sales share,Cars,EV,2011,percent,6.500000e-03
2,Australia,Historical,EV sales,Cars,BEV,2011,Vehicles,4.900000e+01
3,Australia,Historical,EV stock,Cars,BEV,2011,Vehicles,4.900000e+01
4,Australia,Historical,EV stock,Cars,BEV,2012,Vehicles,2.200000e+02
...,...,...,...,...,...,...,...,...
12649,World,Projection-STEPS,EV sales share,Cars,EV,2035,percent,5.500000e+01
12650,World,Projection-STEPS,EV stock share,Cars,EV,2035,percent,3.100000e+01
12651,World,Projection-APS,EV charging points,EV,Publicly available fast,2035,charging points,9.400000e+06
12652,World,Projection-APS,EV charging points,EV,Publicly available slow,2035,charging points,1.500000e+07
12653,World,Projection-STEPS,EV stock share,Trucks,EV,2035,percent,9.000000e+00

Display the first few rows of the DataFrame to understand its structure

In [5]:
global_df.head()

,region,category,parameter,mode,powertrain,year,unit,value
0,Australia,Historical,EV stock share,Cars,EV,2011,percent,0.00039
1,Australia,Historical,EV sales share,Cars,EV,2011,percent,0.00650
2,Australia,Historical,EV sales,Cars,BEV,2011,Vehicles,49.00000
3,Australia,Historical,EV stock,Cars,BEV,2011,Vehicles,49.00000
4,Australia,Historical,EV stock,Cars,BEV,2012,Vehicles,220.00000

Filtering: Select the rows where the 'year' = 2012

In [6]:
df_filter = global_df[global_df.year==2012]
df_filter.head()

,region,category,parameter,mode,powertrain,year,unit,value
4,Australia,Historical,EV stock,Cars,BEV,2012,Vehicles,220.0000
5,Australia,Historical,EV sales,Cars,BEV,2012,Vehicles,170.0000
6,Australia,Historical,EV sales share,Cars,EV,2012,percent,0.0300
7,Australia,Historical,EV stock share,Cars,EV,2012,percent,0.0024
8,Australia,Historical,EV stock,Cars,PHEV,2012,Vehicles,80.0000

Grouping: Group data by 'region' and 'category'

In [7]:
group = df_filter.groupby(['region', 'category'])
group

Aggregating: Calculate the sum of 'value' for each group

In [8]:
agg = group['value'].sum().reset_index()
agg

               region    category          value
0           Australia  Historical     550.032400
1             Austria  Historical    1540.233000
2             Belgium  Historical    2691.748800
3              Brazil  Historical      40.001300
4              Canada  Historical    5085.156180
5               Chile  Historical      26.002380
6               China  Historical   38097.472900
7             Denmark  Historical    3001.165000
8                EU27  Historical   79997.228900
9              Europe  Historical  121080.801198
10            Finland  Historical     421.178600
11             France  Historical   27358.993000
12            Germany  Historical   12685.619000
13            Iceland  Historical      86.349000
14              India  Historical    2992.619245
15             Israel  Historical    1212.299000
16              Italy  Historical    4724.380200
17              Japan  Historical   72211.958700
18              Korea  Historical    1373.051400
19             Mexico  Historical     179.008140
20        Netherlands  Historical   15123.001000
21        New Zealand  Historical     149.438900
22             Norway  Historical   16387.651100
23             Poland  Historical      64.059000
24           Portugal  Historical    2151.111000
25  Rest of the world  Historical    2270.165135
26              Spain  Historical    2150.350500
27             Sweden  Historical    2837.162000
28        Switzerland  Historical    2564.678000
29            Turkiye  Historical      92.016000
30                USA  Historical  141627.384342
31     United Kingdom  Historical   15430.802000
32              World  Historical  391069.803638

In [10]:
agg_sort=agg.sort_values(by='value', ascending = False)
agg_sort

               region    category          value
32              World  Historical  391069.803638
30                USA  Historical  141627.384342
9              Europe  Historical  121080.801198
8                EU27  Historical   79997.228900
17              Japan  Historical   72211.958700
6               China  Historical   38097.472900
11             France  Historical   27358.993000
22             Norway  Historical   16387.651100
31     United Kingdom  Historical   15430.802000
20        Netherlands  Historical   15123.001000
12            Germany  Historical   12685.619000
4              Canada  Historical    5085.156180
16              Italy  Historical    4724.380200
7             Denmark  Historical    3001.165000
14              India  Historical    2992.619245
27             Sweden  Historical    2837.162000
2             Belgium  Historical    2691.748800
28        Switzerland  Historical    2564.678000
25  Rest of the world  Historical    2270.165135
24           Portugal  Historical    2151.111000
26              Spain  Historical    2150.350500
1             Austria  Historical    1540.233000
18              Korea  Historical    1373.051400
15             Israel  Historical    1212.299000
0           Australia  Historical     550.032400
10            Finland  Historical     421.178600
19             Mexico  Historical     179.008140
21        New Zealand  Historical     149.438900
29            Turkiye  Historical      92.016000
13            Iceland  Historical      86.349000
23             Poland  Historical      64.059000
3              Brazil  Historical      40.001300
5               Chile  Historical      26.002380